[package]
name="tinywasm-parser"
version.workspace=true
description="TinyWasm parser"
edition.workspace=true
license.workspace=true
authors.workspace=true
repository.workspace=true

[dependencies]
wasmparser={version="0.206", default-features=false}
log={version="0.4", optional=true}
tinywasm-types={version="0.6.0", path="../types", default-features=false}

[features]
default=["std", "logging"]
logging=["log"]
std=["tinywasm-types/std", "wasmparser/std"]
