[package]
name="tinywasm"
version.workspace=true
description="A tiny WebAssembly interpreter"
edition.workspace=true
license.workspace=true
authors.workspace=true
repository.workspace=true
rust-version.workspace=true
readme="../../README.md"

[lib]
name="tinywasm"
path="src/lib.rs"

[dependencies]
log={workspace=true, optional=true}
tinywasm-parser={version="0.8.0-alpha.0", path="../parser", default-features=false, optional=true}
tinywasm-types={version="0.8.0-alpha.0", path="../types", default-features=false}
libm={version="0.2", default-features=false}

[dev-dependencies]
wasm-testsuite={path="../wasm-testsuite"}
wast={workspace=true}
eyre={workspace=true}
pretty_env_logger={workspace=true}
criterion={workspace=true}
owo-colors={version="4.0"}
serde_json={version="1.0"}
serde={version="1.0", features=["derive"]}

[features]
default=["std", "parser", "logging", "archive"]
logging=["log", "tinywasm-parser?/logging", "tinywasm-types/logging"]
std=["tinywasm-parser?/std", "tinywasm-types/std"]
parser=["tinywasm-parser"]
archive=["tinywasm-types/archive"]
simd=[]
nightly=["tinywasm-parser?/nightly"]

[[test]]
name="test-mvp"
harness=false

[[test]]
name="test-two"
harness=false

[[test]]
name="test-wast"
harness=false


[[bench]]
name="argon2id"
harness=false

[[bench]]
name="fibonacci"
harness=false

[[bench]]
name="tinywasm"
harness=false
